# --- General options --- #

# url is the full website URL
# baseurl is the website's URL without the hostname

# If you are building a GitHub project page then use these settings:
#url: "http://username.github.io/projectname"

url: "https://www.innvt.it"

# Of course don't forget to change the username and projectname to YOUR username and project

# Name of website
title: INNVT

# Short description of your site
description: INNVT

